# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POPapp', '0010_auto_20170102_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='url',
        ),
        migrations.AddField(
            model_name='background',
            name='image',
            field=models.ImageField(default='no-image.png', upload_to=''),
        ),
    ]
