# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POPapp', '0013_auto_20170102_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='name',
            field=models.IntegerField(choices=[(1, ('Facebook', 'circlefacebook')), (2, ('LinkedIn', 'circlelinkedin')), (3, ('Twitter', 'circletwitterbird')), (4, ('Github', 'circlegithubalt')), (5, ('YouTube', 'circleyoutube')), (6, ('Mail', 'circleemail')), (6, ('Instagram', 'circleinstagram'))]),
        ),
    ]
