# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POPapp', '0014_auto_20170102_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='name',
            field=models.CharField(choices=[('circlefacebook', 'Facebook'), ('circlelinkedin', 'Linkedin'), ('circletwitterbird', 'Twitter'), ('circlegithubalt', 'Github'), ('circleyoutube', 'Youtube'), ('circleemail', 'Email'), ('circleinstagram', 'Instagram')], default='', max_length=25),
        ),
    ]
